name: Update README with Recent Activity

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Gerar feed de atividades recentes
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://github.com/JamesCookDev.atom"
          max_post_count: 5
          comment_tag_name: "activity"
          commit_message: "chore: update recent github activity"
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          template: "<li><a href='{url}' target='_blank'>{title}</a> - {date}</li>"
          date_format: "dd/mm/yyyy" 
          user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36"
